export const treatments = [
  {
    name: 'HydraFacial',
    price: 'From $185',
    duration: '60 min',
    desc: 'A multi-step facial that cleanses, exfoliates, extracts, and hydrates using advanced vortex-infusion technology. Suitable for all skin types with immediate, visible results.',
    tags: ['Hydration', 'Anti-Aging', 'All Skin Types'],
  },
  {
    name: 'Chemical Peel',
    price: 'From $120',
    duration: '30–45 min',
    desc: 'Customized acid blends that dissolve dead skin cells to reveal fresher, smoother skin beneath. Available in light, medium, and deep formulations.',
    tags: ['Brightening', 'Resurfacing', 'Acne-Prone'],
  },
  {
    name: 'Microneedling',
    price: 'From $250',
    duration: '75 min',
    desc: 'Collagen induction therapy using micro-fine needles to stimulate the skin\'s natural healing response. Reduces fine lines, acne scars, and uneven texture over a series of sessions.',
    tags: ['Collagen Boost', 'Anti-Aging', 'Scar Reduction'],
  },
  {
    name: 'Microdermabrasion',
    price: 'From $95',
    duration: '45 min',
    desc: 'A gentle physical exfoliation using fine crystals or a diamond-tip wand to remove the outermost layer of skin, revealing a brighter, more even complexion.',
    tags: ['Exfoliation', 'Pore Refinement', 'Dull Skin'],
  },
  {
    name: 'LED Light Therapy',
    price: 'From $65',
    duration: '30 min',
    desc: 'Non-invasive photobiomodulation using targeted wavelengths of light to address acne, inflammation, and signs of aging. Often paired with other treatments.',
    tags: ['Acne Control', 'Anti-Inflammatory', 'Healing'],
  },
  {
    name: 'Dermaplaning',
    price: 'From $90',
    duration: '45 min',
    desc: 'A precision blade gently removes vellus hair (peach fuzz) and dead skin cells, leaving the skin exceptionally smooth and primed for optimal product absorption.',
    tags: ['Smoothing', 'Brightening', 'Peach Fuzz Removal'],
  },
  {
    name: 'Oxygen Facial',
    price: 'From $130',
    duration: '60 min',
    desc: 'Pressurized oxygen delivers a potent serum of vitamins, antioxidants, and hyaluronic acid deep into the skin — providing an instant plumping and luminosity boost.',
    tags: ['Hydration', 'Instant Glow', 'Pre-Event'],
  },
  {
    name: 'Lymphatic Drainage Facial',
    price: 'From $110',
    duration: '60 min',
    desc: 'A relaxing, technique-focused facial that uses gentle manual manipulation to encourage lymphatic flow, reducing puffiness, promoting detoxification, and supporting skin clarity.',
    tags: ['Depuffing', 'Detox', 'Redness Reduction'],
  },
];
